services:
  web:
    build: .
    env_file:
      - .env
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:8000 resumeproject.wsgi:application --workers=4
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media 
    ports:
      - "80:80"
    depends_on:
      - web