# Generated by Django 4.2.4 on 2023-08-31 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(verbose_name='Item')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('work_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.workhistory')),
            ],
            options={
                'verbose_name_plural': 'Job Descriptions',
            },
        ),
    ]
