# Generated by Django 4.2.4 on 2023-08-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.AlterModelOptions(
            name='workhistory',
            options={'verbose_name_plural': 'Work Histories'},
        ),
    ]
