# Generated by Django 4.2.4 on 2023-08-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_rename_skills_skill_alter_workhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/resumes', verbose_name='Resume Picture'),
        ),
    ]
