# Generated by Django 4.2.4 on 2023-08-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_jobdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhistory',
            name='job_description',
            field=models.TextField(blank=True, null=True, verbose_name='Job Description'),
        ),
    ]
