# Generated by Django 5.1.6 on 2025-02-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_delete_jobdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/resumes', verbose_name='Resume Picture'),
        ),
    ]
