# Generated by Django 5.1.6 on 2025-02-12 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.RemoveField(
            model_name='workhistory',
            name='job_description',
        ),
        migrations.AddField(
            model_name='workhistory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.CharField(max_length=7, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.CharField(max_length=7, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='end_date',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='start_date',
            field=models.CharField(max_length=7, verbose_name='Start Date'),
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Skill Group Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.skillgroup'),
        ),
    ]
