# Generated by Django 5.1.6 on 2025-02-12 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_remove_resume_description_resume_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.skillgroup'),
        ),
    ]
