# Generated by Django 5.1.6 on 2025-02-15 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_skillgroup_unique_skillgroup_per_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='skillgroup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skillgroup',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.skillgroup'),
        ),
    ]
