# Generated by Django 5.1.6 on 2025-02-15 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_skill_created_at_skill_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.skillgroup'),
        ),
    ]
