# Generated by Django 4.2.4 on 2023-08-31 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=8, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 19, 6, 45, 164151, tzinfo=datetime.timezone.utc), verbose_name='Token Expires'),
        ),
    ]
