# Generated by Django 4.2.4 on 2023-09-21 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_token_token_alter_token_token_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 8, 32, 55, 489890, tzinfo=datetime.timezone.utc), verbose_name='Token Expires'),
        ),
    ]
