# Generated by Django 4.2.4 on 2025-02-08 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_token_token_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 13, 53, 52, 644244, tzinfo=datetime.timezone.utc), verbose_name='Token Expires'),
        ),
    ]
