# Generated by Django 4.2.4 on 2025-02-09 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_token_token_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 9, 15, 8, 42, 460142, tzinfo=datetime.timezone.utc), verbose_name='Token Expires'),
        ),
    ]
